data:
# -- put your schema here -- #

# -- these are for the security filter -- #

  user:
    _attributes:    { phpName: User, authenticator: true }
    _orderby:       [ username, name ]
    _listcolumns:   [ username, name ]
    _searchon:      [ name, address, postcode, username, email ]
    id:             { type: int, required: true, primaryKey: true, autoincrement: true }
    name:           { type: varchar, size: 255, required: true }
    username:       { type: varchar, size: 255, required: true, searchable: true, confirm: true }
    email:          { type: varchar, size: 255, required: true, searchable: true, confirm: true }
    password:       { type: varchar, size: 255, required: true, confirm: true }
    md5word:        { type: varchar, size: 255, required: true, calculated: "md5($this->GetPassword())" }
    activated:      { type: tinyint, required: true }
    usergroup:      { type: int, required: true, linkedObject: Usergroup, dbFieldName: usergroup }
    
  usergroup:
    _attributes:    { phpName: Usergroup }
    _listcolumns:   [ name, level ]
    _orderby:       [ level desc ]
    id:             { type: int, required: true, primaryKey: true, autoincrement: true }
    name:           { type: varchar, size: 255, required: true }
    level:          { type: int, required: true, searchable: true }
    
  task:
    _attributes:    { phpName: Task }
    _orderby:       [ controller, function ]
    _listcolumns:   [ controller, function, usergroup->name ]
    id:             { type: int, required: true, primaryKey: true, autoincrement: true }
    controller:     { type: varchar, required: true, size: 255 }
    function:       { type: varchar, required: true, size: 255 }
    usergroup:      { type: int, required: true, linkedObject: Usergroup }
