default:
  db:
    host:            localhost
    name:            databasename
    user:            username
    pass:            password

  app:
    location:        http://localhost/website.co.uk
    public_location: http://localhost/website.co.uk
    title:           Website Title
    author:          David Hamilton
    company:         Something Easy To Remember
    
    default_lang:      English
    mod_rewrite:       true
    unicode:           false
    cookiename:        prefix
    history:           true
    extension:         html
    date_format:       l d.m.y
    summary_delimiter: \{more\}
    error_tag:         p
    error_tag_attr:    class='error'
    
  epdq:
    post_url:          https://localhost/skirmishpaintball.co.uk/booking/fake.html
    enc_server:        secure2.epdq.co.uk
    enc_url:           /cgi-bin/CcxBarclaysEpdqEncTool.e
    clientid:          
    passphrase:        
    currencycode:      826
    deliveryaddress:   0

  date_formats:
    default:         d/m/Y
    offer:           l d.m.y

  mail:
    enabled:         true
    name:            SETR Info
    address:         david@orqi.co.uk
    
  image:
    upload_thumbnail: { x: 30, y: 30, orientation: CM, scale: fit, default: /somepic.gif }
    upload_preview:   { x: 300, y: 200, orientation: CM, scale: fit, default: /somepic.gif }
    lifestylepic:     { x: 558, y: 365, orientation: CM, scale: fit, default: /somepic.gif, overlay: /overlay_large.png }
    thumbnail:        { x: 100, y: 69, orientation: CM, scale: fit, default: /somepic.gif, overlay: /overlay_small.png }
    
  page:
    items:           20
    users:           10
    tasks:           30
    
  filetypes:
    default:         { type1: image/jpeg, type2: image/jpg, type3: image/gif, type4: image/png }
    downloads:       { type1: application/pdf, type2: application/msword }

  filters:           [Security]

  classes:
    domain:          _classes/_domain
    mapper:          _classes/_mapper
    validator:       _classes/_validator
    app:             _classes/_app
    inf:             _classes/_inf
    ui:              _classes/_ui
    filter:          _classes/_filters
    
  image_uploader:
    photo_upload_url:  /skirmishadmin.co.uk/upload/photo.html
    file_upload_url:   /skirmishadmin.co.uk/upload/file.html
    uploader_swf:      /skirmishadmin.co.uk/_js/yui/uploader/assets/uploader.swf
    
  base:
    domain:          _base/_domain
    mapper:          _base/_mapper
    validator:       _base/_validator
    app:             _base/_app
    
  resource:
    url:             http://localhost/website.co.uk/_resources
    path:            /home/maracuja/htdocs/website.co.uk/_resources
    img:             http://localhost/website.co.uk/_img
    imgpath:         /home/maracuja/htdocs/website.co.uk/_img
    css:             http://localhost/website.co.uk/_css
    js:              http://localhost/website.co.uk/_js
    swf:             http://localhost/website.co.uk/_flash
    lib:             _lib
    lib_url:         http://localhost/website.co.uk/_lib

